### ISSUE TITLE
Expand the list of frontend template options

### ISSUE THREAD

**Issue by fyodorio** [stellar/stellar-docs#1034]
### What problem does your feature solve?
`contract init` command (https://developers.stellar.org/docs/tools/stellar-cli#stellar-contract-init) provides a flag (`--frontend-template`) allowing to generate UI code for contracts _via a repository_ (if I'm not mistaken). But there's only one [publically-available/searchable] template now (https://github.com/stellar/soroban-astro-template) and no specific pointers on where to find other options, or how to create them (minimal requirements for such a repo?)

### What would you like to see?
Other options/examples for UI generation, or short documentation on how to create one (for instance, with Preact, Svelte, Vue, or whatnot)

### What alternatives are there?
Manual creation? Which probably requires a lot more stuff to take care of...

**Comment by janewang** [comment]
Discussed with @ElliotFriend and moved to the docs repo where frontend templates will be listed
