### ISSUE TITLE
RSS support for blog

### ISSUE THREAD

**Issue by kuchta** [stellar/stellar-docs#1062]
Please implement RSS support for [stellar.org/blog](https://stellar.org/blog) so we can follow.

**Comment by ElliotFriend** [comment]
Hi, @kuchta! RSS is already enabled and supported on the stellar.org site. You can find it here: https://stellar.org/blog/rss.xml

Though, as a point of clarification, _this_ repository isn't related to the content on the `www.stellar.org` website.

**Comment by kuchta** [comment]
@ElliotFriend Thank you for the link, but it would be appropriate if it's also linked in blog page head to be auto-discoverable by readers.

I know this respository is not related to content on the www.stellar.org, but I haven't found any one which is and your answer didn't help either.

**Comment by briwylde08** [comment]
@kuchta do you mean in the page head html and not in the hero/header?

**Comment by kuchta** [comment]
Yes @briwylde08, like this:

```
<head>
  <link rel="alternate" type="application/rss+xml" href="ttps://stellar.org/blog/rss.xml" />
</head>
```

**Comment by briwylde08** [comment]
@kuchta got it, I'll relay this back to our dig marketing team. I don't think there's any way currently for you to submit feedback like you can on GH for the stellar.org site, but you can feel free to tag me on Disc if you notice anything else and I'll at least try to address it / take it back to the team. Discord is .aythia

**Comment by kuchta** [comment]
Thank you @briwylde08, I appreciate it ❤️
