### ISSUE TITLE
Horizon compute pre-requirements

### ISSUE THREAD

**Issue by sreuland** [stellar/stellar-docs#143]
### What problem does your feature solve?
The https://developers.stellar.org/docs/run-api-server/prerequisites has a lot of information, some duplication and obsolete facets may be present and may be difficult for readers to make correct conclusions for current day horizon capabilities.

### What would you like to see?
Simplify/condense compute requirements tables stated for catch-up and real-time ingestion down to single section for horizon and db. Follow a more opinionated stance to reduce the amount of overall content, try to avoid explaining all settings individually, instead just state the combination that is recommended and why. 

Focus recommendation towards `on-disk mode of captive core and don't mention in-memory settings. Describe why IOPSon the volume used to host captive core db needs to be fast SSD, and highest IOPS can afford, bare min of at least 3k r/w a second.

Mention ballpark estimates on how much it will be expected to cost in terms of compute, for those considering a cloud deployment.

**Comment by urvisavla** [comment]
@sreuland @mollykarcher  A couple of clarifications on the scope here:
 
> Simplify/condense compute requirements tables stated for catch-up and real-time ingestion down to single section for horizon and db. 
1. For real-time ingestion, are the current production cluster specs suitable, or should we run tests on the  new dev/test cluster for the specs?
2. For historical ingestion, should we display specs for all 30/60/full days, or should we make a recommendation for the number of history days and only provide corresponding hardware specifications? 



>Mention ballpark estimates on how much it will be expected to cost in terms of compute, for those considering a cloud deployment.

Should this be specific to AWS or include other cloud providers as well?

**Comment by sreuland** [comment]
> Should this be specific to AWS or include other cloud providers as well?

I don't think we should reference any cloud vendors, rather, if we can keep reference to resources more at the commodity level, like RAM, CPU cores and disk throughput, ideally can translate into vendor specifics. 

For disk throughput, AWS uses`IOPS` which we've ref'd in benchmarking disk speeds related to captive core on-disk and have stated in a few places min of 3k IOPS, but that metric is ops per second, and we also need to back that with some type of associated physical bytes/sec also, which AWS assumes 1kb per op, which is decent way to extrapolate min r/w throughput of disk volume at about `3 mb/s = 3k IOPS x 1024 bytes per op`

**Comment by gre3n3yes34** [comment]
Where is my withdrawal  button on the stellarscan.com website
