### ISSUE TITLE
Update code snippets in LP example docs

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#211]
Users are encountering errors when going through the Examples on this page: https://developers.stellar.org/docs/encyclopedia/liquidity-on-stellar-sdex-liquidity-pools#examples. 

We need to update code snippets to avoid further errors. See specific conversation here: https://discord.com/channels/897514728459468821/907476473739354153/1137130480454610964

**Comment by ElliotFriend** [comment]
Working on resolving this week. In the meantime:

A working script can be pieced together using the code examples from [Stellar Quest, Level 3, Quest 5](https://quest.stellar.org/learn/series/3/quest/5). Note that the runkit at the bottom of the page is _intentionally_ not a "ready-to-run" script. However, if you put together all the snippets throughout the code instructions, you should get something that "works."

**Comment by ElliotFriend** [comment]
It also appears the python code snippets on that docs page are still working

**Comment by ElliotFriend** [comment]
For anyone following, PR #214 contains the fixes for the JS snippets. The preview is available here: https://developers-pr214.previews.kube001.services.stellar-ops.com/docs/encyclopedia/liquidity-on-stellar-sdex-liquidity-pools#examples

If you want to see/use the whole script in one "chunk" it's posted on runkit here: https://runkit.com/elliotfriend/64e4dab3a5dd27000801ffdf
