### ISSUE TITLE
Stellar-core install instructions: add package instructions

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-docs#258]
The docs state that stellar-core can be installed from Ubuntu packages, but don't provide any instruction on how to do that, or what the custom apt repo is.

I think we should tell people what they need to do to configure the Stellar apt repo, as well as how to install the packages if we're discussing the package installation method here.

https://github.com/stellar/stellar-docs/blob/e9a03c00f91ddd832043c1f4a395721dd2ce0ffe/docs/run-core-node/installation.mdx#L42-L46

**Comment by janewang** [comment]
Can close by admin guide pushed by Elliot
