### ISSUE TITLE
Stroop is one millionth

### ISSUE THREAD

**Issue by lmorgan824** [stellar/stellar-docs#290]
https://developers.stellar.org/docs/encyclopedia/fees-surge-pricing-fee-strategies

### What did you expect to see?
Stroop: the smallest unit of a lumen, one millionth of a lumen (.0000001 XLM).

### What did you see instead?

Stroop: the smallest unit of a lumen, one ten-millionth of a lumen (.0000001 XLM).

**Comment by gre3n3yes34** [comment]
Ok I need an withdrawal  button

**Comment by briwylde08** [comment]
Hi there! One stroop is actually one ten-millionth of a lumen (.0000001). 

Reference: https://github.com/stellar/stellar-xdr/blob/bb54e505f814386a3f45172e0b7e95b7badbe969/Stellar-ledger.x#L74

You can see that `10,000,000 stroops in 1 XLM`

And .0000001 equals one ten-millionth. Reference: http://academics.wellesley.edu/Astronomy/kmcleod/Toolkit/scinot.html

**Comment by lmorgan824** [comment]
Yes, my bad. I'm blind; I miscounted the decimal places. LOL

Regards,
Lou

**Comment by briwylde08** [comment]
No worries!!
