### ISSUE TITLE
Incorrect link to Horizon API from Stellar Laboratory - Explore endpoints 

### ISSUE THREAD

**Issue by asusmsk** [stellar/stellar-docs#300]
### What version are you using?

Page https://laboratory.stellar.org/#explorer

### What did you do?

Clicked the link "REST API endpoints"

### What did you expect to see?

https://developers.stellar.org/api/horizon

### What did you see instead?

https://developers.stellar.org/api/introduction

**Comment by briwylde08** [comment]
Thanks for the flag! We'll get this taken care of.

**Comment by gre3n3yes34** [comment]
Looking for  accounts

**Comment by briwylde08** [comment]
Fixed with: https://github.com/stellar/laboratory/pull/739

Thank you!
