### ISSUE TITLE
Remove the wrapping concept of assets

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-docs#301]
The docs discuss the concept of "wrapping" assets with contracts, but this concept is old from long ago and no longer part of the vocabulary we or others should be using to talk about deploying Stellar Asset contracts.

When a Stellar Asset Contract is deployed, it doesn't wrap the Stellar Asset. Wrapping would create a second token that can be wrapped/unwrapped or exchanged for the original asset.

The Stellar Asset Contract is an API to control the one-and-only Stellar Asset. The contract allows you to take the asset from trustlines directly out of Stellar classic Accounts, and send it to other classic accounts, or send it to contracts, etc. It's first-class access to assets on Soroban.

Unfortunately we left this concept of 'wrapping' in the CLI by accident and I think it led to proliferation of that terminology and concept here. The command has been deprecated in the CLI and we need to refocus how we talk about the Stellar Asset Contract everywhere.

Page I think needs updating:
- https://developers.stellar.org/docs/fundamentals-and-concepts/stellar-data-structures/assets

Related:
- https://github.com/stellar/soroban-docs/issues/716
- https://github.com/stellar/soroban-tools/issues/934

**Comment by briwylde08** [comment]
Thanks Leigh, I'll get this wording removed.
