### ISSUE TITLE
Rewrite Welcome page

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#328]
### What problem does your feature solve?

Combines the Soroban and Stellar Welcome pages for a more cohesive introduction to the merged docs

https://soroban.stellar.org/docs/
https://developers.stellar.org/docs

### What would you like to see?

A landing page that incorporates both Stellar and Soroban information

**Comment by janewang** [comment]
According to @ElliotFriend, this is in progress

**Comment by briwylde08** [comment]
Also include: https://github.com/stellar/stellar-docs/issues/344

**Comment by briwylde08** [comment]
PR: https://github.com/stellar/stellar-docs/pull/384
