### ISSUE TITLE
Restructure Fully-Typed Contracts section into a How-To Guide

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#333]
### What problem does your feature solve?

Fully-Typed contracts (https://soroban.stellar.org/docs/soroban-internals/types/fully-typed-contracts) doesn't entirely fit into the Types section and has more guide content. 

### What would you like to see?

We'd like to tweak it and move it to the How-To Guides section as "Generate Contract Spec"

**Comment by janewang** [comment]
@chadoh What do you think of the current page?
