### ISSUE TITLE
Refresh the Fee-Bump Transaction section

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#335]
Get up to $100 worth of XLM

### What problem does your feature solve?

We have examples for most Stellar functions, but not for fee-bumps. We'd like to ensure this section also has an example.

### What would you like to see?

Create a fee-bump example. Make sure the content in this section is still correct. https://developers.stellar.org/docs/encyclopedia/fee-bump-transactions

**Comment by rahul-soshte** [comment]
@briwylde08 Please assign me this issue

**Comment by briwylde08** [comment]
You got it!

**Comment by rahul-soshte** [comment]
Yes i have submitted the form
