### ISSUE TITLE
Create content that explains differences between various RPC providers

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#343]
### What problem does your feature solve?

Help users understand what RPC provider is better for their use case. OG discussion here:

https://discord.com/channels/897514728459468821/1209144882652778496/1209160426865299486

### What would you like to see?

Key features that distinguish between the various RPC providers

**Comment by Phenzic** [comment]
Hi @briwylde08 Just playing around and saw these treats, I'd like to get my hands dirty with them if that's cool, 
I do have a couple of questions though, but I'd also like start contributing with this piece, If you don't mind assigning them to me 🥂

**Comment by briwylde08** [comment]
Hey @Phenzic! Of course, go right ahead! Feel free to ask questions, but I'll be out of town for a while so tag @janewang or @ElliotFriend!

**Comment by janewang** [comment]
Hi @Phenzic Thank you for considering contributing to the Dev Docs! 🚀 We appreciate your contribution. Please feel free to open a PR and ping myself and @ElliotFriend for review. 👍

**Comment by Phenzic** [comment]
Happy to contribute... Just got started with the task
I just have a couple of questions
For starters do I add the article to the docs section or the developer blog section

**Comment by janewang** [comment]
I recommend developer docs as they are evergreen content.
