### ISSUE TITLE
Create developer paths on the docs landing page

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#344]
### What problem does your feature solve?

Help users navigate the docs right away by adding paths to the landing page.

### What would you like to see?

Stellar 101 (Learn -> Fundamentals)
Write a Smart Contract (Smart Contracts - Getting Started)
Issue an Asset (Docs - Issue Asset Tutorial)
Build an Application (Docs -> Build Applications)
Developer Tools (Tools -> Developer Tools)
Access Data (Platforms -> RPC)

**Comment by Phenzic** [comment]
Can I also get these assigned to me, I'd love to contribute 🥂

**Comment by janewang** [comment]
Assigned to you @Phenzic
