### ISSUE TITLE
Add versioning to Anchor Platform documentation

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#345]
### What problem does your feature solve?

Request from Jake and Gleb: we'd like to include versioning to the Anchor Platform documentation. Elliot is working on it!

### What would you like to see?

Be able to make different versions of documentation accessible and useable. Currently in conversation between Gleb and Elliot (primarily).

**Comment by janewang** [comment]
@JakeUrban Is this an urgent ask?

**Comment by JakeUrban** [comment]
It is not urgent my understanding is that it is not a significant lift to support. @ElliotFriend would have the best idea.

**Comment by Ifropc** [comment]
We want this task to be done before any significant work on SEP-6 is being done, IMO (I don't think the work on SEP-6 feature will start before Q2)

**Comment by ElliotFriend** [comment]
Saving for future reference: https://stackoverflow.com/questions/75229184/docusaurus-how-can-i-have-multiple-versions-of-different-docs-in-the-docs-direc
