### ISSUE TITLE
Missing docs on rate-limit config in Horizon's captive-core

### ISSUE THREAD

**Issue by borisovano** [stellar/stellar-docs#348]
### What version are you using?
V2.28.3

### What did you do?

We manage our own Horizon node, it spawns a separate captive-core process.
We are encountering some 429s (rate limiting)
https://developers.stellar.org/api/horizon/introduction/rate-limiting

Is it a soft limit that can be controlled by configuration, if yes can you help where?
The reason I ask is that we see that stellar-core.conf is autogenerated by/for the captive-core process and we can't find how to change/inject this configuration.

We checked this docs however rate-limit is not mentioned there:
Core: https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_example.cfg
Horizon: https://developers.stellar.org/docs/run-platform-server/configuring

### What did you expect to see?
Clear docs on how to change config of captive core

### What did you see instead?
No documentation on the above

**Comment by mollykarcher** [comment]
@borisovano the stellar core configuration is indeed autogenerated by Horizon. Horizon only exposes some subset of the configuration provided by core, which it will then translate into the core config file it generates. 

In this particular case though, the rate limiting is a Horizon configuration. The value you are looking for is `PER_HOUR_RATE_LIMIT`. You can disable it entirely by setting it to 0 (ie. PER_HOUR_RATE_LIMIT=0 ), the default is 3600 req/s, but you'll probably want to tune it to your own infrastructures capabilities and client/request needs. We'll update the rate limiting docs [here](https://developers.stellar.org/network/horizon/api-reference/structure/rate-limiting) to make this clear.
