### ISSUE TITLE
Deprecated method 'Network.useTestNetwork()` in documentation

### ISSUE THREAD

**Issue by hanseartic** [stellar/stellar-docs#35]
### What version are you using?
Latest docs online (main-branch).

### What did you do?
The JS example for the [channel-accounts ](https://developers.stellar.org/docs/encyclopedia/channel-accounts) documentation uses an outdated method `Network.useTestNetwork()`.

### What did you expect to see?
Usage of up-to-date code in example-snippet (as suggested in #34).
 
### What did you see instead?
Usage of outdated code in example snippet:
![grafik](https://user-images.githubusercontent.com/1752217/189890774-6bba8455-ace9-4ad6-ad63-0938001b71ad.png)

**Comment by briwylde08** [comment]
Thanks for the issue and PR, we just merged it: https://github.com/stellar/stellar-docs/pull/34
Should be live shortly.
