### ISSUE TITLE
Embed Canvas inclusion fee to docs

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#369]
### What problem does your feature solve?

Inclusion fees change a bit with smart contracts in that users can expect to pay their full inclusion fee with smart contract transactions more so than with "classic" Stellar transactions. 

It would be good to show this with a few examples so users can understand it better.

### What would you like to see?

Add examples to our docs around inclusion fees. (what happens when there are 3 transactions each with a different max bid; what happens with classic traffic is high), etc.

**Comment by janewang** [comment]
The plan here is to embed canvas
