### ISSUE TITLE
Add preview links and logo for social media platforms

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#393]
### What problem does your feature solve?
Stellar docs are not rendering well on twitter, or facebook

<img width="984" alt="Screenshot 2024-03-27 at 11 12 49 AM" src="https://github.com/stellar/stellar-docs/assets/734336/15d057dd-5e96-41f6-a3d6-112fb5f39f41">

### What would you like to see?
Add meta tags for twitter and facebook such that the links will render in preview on Twitter an Facebook

**Comment by janewang** [comment]
Docs from twitter here https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

**Comment by ElliotFriend** [comment]
Here's how/where to configure the setting in Docusaurus' `themeConfig` object: https://docusaurus.io/docs/2.x/api/themes/configuration#meta-image
