### ISSUE TITLE
"Soroban Dapps Challenge" should be migrated from soroban docs repo

### ISSUE THREAD

**Issue by ElliotFriend** [stellar/stellar-docs#406]
The final remaining content in the [stellar/soroban-docs](/stellar/soroban-docs) repository is the "Dapps" section, containing all of the dapps challenge content.

Since the soroban docs used a version of docusaurus that was (slightly) ahead of this repo, we ran into some version mismatches that prevented the easy migration. I think once #405 gets approved and merged, we'll be in a pretty good place to give it another go. I think the version mismatch problems will all but disappear.

**Comment by ElliotFriend** [comment]
An initial attempt was made, and it seems like the package upgrades will indeed make this much easier

**Comment by briwylde08** [comment]
Note from original dapps challenge issue: https://github.com/stellar/stellar-docs/issues/342

- Put the actual Dapps Challenge in "Interactive Learning" under the "Learn" section.
- Put Dapps section and Scaffold Soroban section into How-To Guides.
