### ISSUE TITLE
Automatically generate API method examples

### ISSUE THREAD

**Issue by 2opremio** [stellar/stellar-docs#412]
Generating the sample JSON requests and responses is pretty laborious manual task.

**Comment by janewang** [comment]
I think we are want enable curling against an endpoint to get a JSON examples. We are removing horizon mainnet url and not providing RPC mainnet. So we can only provide testnet samples. Testnet is reset intermittently. 

Giving the builder a way to curl against an endpoint locally should suffice and is the case for a lot of API docs.
