### ISSUE TITLE
cross contract calls: document the non panicking version

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-docs#413]
Our current cross contract call example panics when the called contract panics.

However, often times the calling contract would be interested in handling the error, rather than panicing. It would be beneficial to either add this to our existing cross contract how-to or potentially somewhere else.

For example, instead of this call, which will panic when `add()` panics:

```rust
let client = contract_a::ContractClient::new(&env, contract_id);
client.add(&x, &y)
```

We can introduce something like this call, which will return 0 when `add()` panics:

```rust 
let client = contract_a::ContractClient::new(&env, contract_id);
client.try_add(&x, &y).unwrap_or(Ok(0)).unwrap()
```

**Comment by tupui** [comment]
This 👍 And also if I can add something (was not sure about making a new issue for it), it would be good to show usages of `invoke_contract` and `try_invoke_contract` by extension. Plus a discussion on pros/cons like fees.

(I was looking if there was a bounty entry for cross contract calls as I now spent some time playing around and could have tried to contribute. Regardless, happy to try and take a stab at it if wanted.)

**Comment by briwylde08** [comment]
@janewang, I see this has been labeled as part of the Horizon scrum, do you know if this is being worked on internally?

**Comment by janewang** [comment]
It does not appear to be. I added to the Dev X docpocalyse so perhaps we could get to it this week.

**Comment by briwylde08** [comment]
@tupui: feel free to take this one! We'll offer $150 worth of XLM for the docs bounty!

**Comment by tupui** [comment]
Thanks! Starting right away

**Comment by tupui** [comment]
I opened a PR 😃 #853 Thanks again all!

**Comment by briwylde08** [comment]
Thanks again for your contribution @tupui! Your bounty submission has qualified for $150 worth of XLM. Is the previously summitted information still valid for your award payment?

**Comment by tupui** [comment]
All is still valid. Thanks again everyone, that was a fun program to participate in 😃
