### ISSUE TITLE
[Post merge cleanup] Add definiton of Soroban in the glossary

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#414]
### What problem does your feature solve?
We use the name “Soroban” throughout the documentation but never explain it. In the Soroban docs, we talked about the name and its origin. Let's move that over

**Comment by janewang** [comment]
PR opened https://github.com/stellar/stellar-docs/pull/417

**Comment by briwylde08** [comment]
@janewang I think we can close this one with the new Soroban glossary entry. Need to keep in mind that we will need to change the official definition of Soroban to include only the runtime environment. This is mostly relevant for our Welcome page.

**Comment by janewang** [comment]
Agreed, closing
