### ISSUE TITLE
Add information on how to use stellar-etl to obtain historical data to hubble docs

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#421]
### What problem does your feature solve?

Looking for a word doc or PR on ingesting historical data
[  ] How to use stellar-etl to obtain historical data from hubble
[  ] Discuss ledger exporter as a potential future option

**Comment by ElliotFriend** [comment]
#669 Seems to have accomplished this. @janewang If the [content here](https://developers.stellar.org/docs/data/hubble/admin-guide/source-system-ingestion/getting-started) doesn't quite fit what you have in mind, feel free to reopen the issue.
