### ISSUE TITLE
Freighter docs should encourage connecting to Testnet instead of Futurenet

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-docs#425]
### What version are you using?

4efc0188d00d7b7b6ff165a109dc4e4630a8182b

### What did you do?

Go to https://developers.stellar.org/docs/smart-contracts/guides/freighter.

### What did you expect to see?

<img width="457" alt="Screenshot 2024-04-04 at 9 28 23 pm" src="https://github.com/stellar/stellar-docs/assets/351529/79af2e80-95aa-4f68-9ad4-2d7c0db16efe">

### What did you see instead?

<img width="457" alt="Screenshot 2024-04-04 at 9 28 31 pm" src="https://github.com/stellar/stellar-docs/assets/351529/c54f239b-4897-4fca-88fb-6cc1fbfd8617">

### Discussion

Testnet is the place that most developers should be building if not locally. Futurenet is for bleeding edge experimental testing that now that Soroban has made it to testnet and mainnet. Also Futurenet is an unstable test environment, so it will be often that folks try to connect to it and it'll be in a different state they expect if they're just looking for a place to test.

cc @piyalbasu

**Comment by piyalbasu** [comment]
Thanks for pointing this out @leighmcculloch . Addressed in this PR: https://github.com/stellar/stellar-docs/pull/435/files

**Comment by janewang** [comment]
Closed by the PR
