### ISSUE TITLE
Soroban looks interesting, it would be great if there are more documents and live demos

### ISSUE THREAD

**Issue by johnnynanjiang** [stellar/stellar-docs#430]
I'd look for more documents and samples for demonstrating how Soroban works.

**Comment by briwylde08** [comment]
Hi there! We're definitely aware that we need to produce more content to demonstrate how Soroban works in the docs. We plan on running a community-driven content bounty for How-To Guides specifically in the coming months. 

Some other good resources:

- https://fastcheapandoutofcontrol.com/tutorial (learn the basics of Soroban in a gamified environment)
- https://stellar.org/blog/developers (general information regarding developing on Stellar and Soroban)
- https://www.youtube.com/@SorobanOfficial/videos (has some tutorial content)
- And probably the best resource is watching the Soroban channels in our Dev Discord: https://discord.gg/stellardev
