### ISSUE TITLE
Add an Admin interface section to the Stellar Asset Contract 

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-docs#431]
### What problem does your feature solve?

The only current documentation on the admin interface is in https://docs.rs/soroban-sdk/latest/soroban_sdk/token/struct.StellarAssetClient.html. The [Stellar Asset Contract](https://soroban.stellar.org/docs/tokens/stellar-asset-contract) docs should have a section discussing it as well.

**Comment by janewang** [comment]
Closing this as we have a document in progress
