### ISSUE TITLE
Update Getting Started Kit to use the Stellar wallets kit

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#443]
Add to  [Getting started guide](https://soroban.stellar.org/docs/getting-started/create-an-app) here to use the wallet selector kit: https://github.com/Creit-Tech/Stellar-Wallets-Kit

Context: https://docs.google.com/document/d/1zkWiCiGtLn6rCvlGI5JvulSA_1PG4KFwfqnbnIPiDTE/edit

Related issue: https://github.com/Creit-Tech/Stellar-Wallets-Kit/issues/29

**Comment by janewang** [comment]
This is a Q2 OKR Item!

**Comment by briwylde08** [comment]
Duplicate. Closing in favor of: https://github.com/stellar/stellar-docs/issues/443

**Comment by janewang** [comment]
@briwylde08 You are closing this issue in favor of itself? This issue is 443. Is there another issue that you are referring to?

**Comment by briwylde08** [comment]
linked the wrong one by accident. https://github.com/stellar/stellar-docs/issues/766

**Comment by janewang** [comment]
Great, got it, thank you
