### ISSUE TITLE
Use consistent link formats throughout the documentation

### ISSUE THREAD

**Issue by ElliotFriend** [stellar/stellar-docs#454]
While Docusaurus does provide an [opinionated suggestion](https://docusaurus.io/docs/markdown-features/links) for formatting links between markdown documents, our docs use a bunch of different ways in a bunch of different places. **ALL** existing links should be reviewed, and modified if necessary, to ensure a consistent method of linking between pages.

This is somewhat complicated by the fact that different plugins require slightly different nomenclature (see issue #453), but we should create, implement, and communicate a consistent pattern of usage.

**Comment by briwylde08** [comment]
Related PR: https://github.com/stellar/stellar-docs/pull/457

**Comment by briwylde08** [comment]
Closed with completion of https://github.com/stellar/stellar-docs/pull/457
