### ISSUE TITLE
Integrate Stellar CLI docs into Consolidated Developer Docs

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#468]
Integrate CLI docs into Consolidated Developer Docs, making them searchable and easily accessible

```[tasklist]
### Tasks
- [ ] Add more examples for each command
```

**Comment by fnando** [comment]
* pr for stellar-cli: https://github.com/stellar/stellar-cli/pull/1435
* pr for stellar-docs: https://github.com/stellar/stellar-docs/pull/755
