### ISSUE TITLE
Update `create-an-app` article with new CLI version

### ISSUE THREAD

**Issue by ElliotFriend** [stellar/stellar-docs#473]
The "Create An App" article has [some instructions](https://soroban.stellar.org/docs/getting-started/create-an-app#generate-an-npm-package-for-the-hello-world-contract) regarding the `soroban contract bindings` command in `v0.9.4`.

Assuming those caveats and workarounds are no longer needed, we should update/modify/remove language here as necessary to reflect the new release.

@chadoh Can you update this page as needed? If you don't have time with Meridian coming up, I can get a PR started for you to review?

**Comment by chadoh** [comment]
@ElliotFriend i see this was created quite a long time ago. While an update to the docs is needed again, I wonder if it’s better to create a new tracking issue and to close this one. The detail about v0.9.4 is confusing, at this point.

**Comment by janewang** [comment]
Can close
