### ISSUE TITLE
Docs: comparison with other systems

### ISSUE THREAD

**Issue by graydon** [stellar/stellar-docs#474]
I was chatting with a friend today and I showed them the soroban docs and they said they wanted to know how it compared to other smart contract platforms, especially wasm-based ones (cosmwasm, solana, elrond, etc.)

I think this would be a useful thing to add to the learn section, for people who want a quick summary and don't want to have to build a mental model of all the systems from the bottom up.

**Comment by janewang** [comment]
Does [this](https://developers.stellar.org/docs/learn/migrate/evm) meet your needs or do you think there are more info to be added?

**Comment by briwylde08** [comment]
Reference: https://github.com/stellar/stellar-docs/issues/339
