### ISSUE TITLE
Add Dependabot to our docs 

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#479]
### What problem does your feature solve?
Once the docs are upgraded to docusaurus 3 and our dependencies are updated to new versions, we could add dependabot to automatically let us know which packages are outdated. For example, currently[ this package](https://github.com/stellar/stellar-docs/pull/373) is currently outdated and cause issues during `yarn install`

**Comment by ElliotFriend** [comment]
@janewang I saw #769 this morning. Does that mean we've got dependabot setup already? I think since we're pretty close on docusaurus v3, we might want to wait on it if we can?

**Comment by janewang** [comment]
Yes I supposed the bot is here

**Comment by ElliotFriend** [comment]
Closing now that we have docusaurus v3 (#752) and I just merged the first dependabot PR (#775)
