### ISSUE TITLE
Docs: Claim Claimable Balance page not clear about required trustline (for non-native assets)

### ISSUE THREAD

**Issue by jonbeebe** [stellar/stellar-docs#48]
### What version are you using?

Latest public docs site:
https://developers.stellar.org/docs/encyclopedia/claimable-balances#claim-claimable-balance

### What did you do?

We were running into "op_no_trust" issues when attempting to claim an asset that destination account did not trust. We incorrectly assumed that claiming a claimable balance would also establish a trustline, but were incorrect. Clearer messaging about this in the docs would have saved us some time and trial/error.

The above linked page implies this, but it could be more explicit:

> The balance on the entry will be moved to the source account if there are no limit or trustline issues (for non-native assets).

### What did you expect to see?

A note underneath that line that says something to the effect of:

> For non-native assets, claimant account must have a trustline to the asset or claim will result in `op_no_trust` error.

### What did you see instead?

No mention in the docs (that I could find) where it says a trustline must first be established before a balance can be claimed (for non-native assets).

**Comment by briwylde08** [comment]
Thank you for this! I changed the language to make it more clear that the claimant must establish a trustline to the asset before they are able to claim the claimable balance. (https://github.com/stellar/stellar-docs/pull/49)
