### ISSUE TITLE
Revisit a way to automate and/or verify the rpc docs

### ISSUE THREAD

**Issue by paulbellamy** [stellar/stellar-docs#488]
### What problem does your feature solve?

We might forget to update the docs to match as we change soroban-rpc.

### What would you like to see?

Automatic generation or at least verification that the docs match the API as expected. This is an "eventually" wishlist item following on from https://github.com/stellar/soroban-docs/issues/247, where there is some previous work linked.

### What alternatives are there?

Do it manually

**Comment by janewang** [comment]
Closing because Platform team will open docs ticket when API changes to inform that there are upcoming changes to the API
