### ISSUE TITLE
Add guides

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-docs#490]
I think need to add a "Guides" section that provide education about how to do certain things at a higher level, and across a broader set of tools including wallets.

Right now the docs are really narrowly focused on specific areas. At the moment only one area: building the contracts themselves. Soon another narrow area: building dapps.

We don't have any documentation that tackle the bigger topics that @tyvdh has been highlighting need addressing:
- Asset issuance and management
- Using assets across Stellar and Soroban

The idea with the Guides is that they form higher level education, but are still focused on step-by-step instruction.

These guides ideally need to cover some categories, and within those categories there are specific more narrow tasks we need to be teaching:

- [ ] Category: Asset Issuance
    - [ ] How to issue an asset on Stellar
    - [ ] How to create a token on Soroban for that asset
    - [ ] How to mint
    - [ ] How to burn / clawback
- [ ] Category: Asset Use
    - [ ] How to import / export
    - [ ] How to make payments
    - [ ] ?

I imagine there are many more topics than this, so anyone is welcome to please update this list.

cc @tomerweller @tyvdh

**Comment by janewang** [comment]
Bri has a doc for the remaining

Asset issuance and management
Using assets across Stellar and Soroban

Closing
