### ISSUE TITLE
Docs Merge Structure v2 ideas

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#494]
### What would you like to see?

1. Change main "Docs" tab to "Build" and have it split into two sections: Smart Contracts and Applications;
2. Create new "Tokenization" main tab and include the [issue assets section](https://developers.stellar.org/docs/category/issue-assets) and [tokens section](https://developers.stellar.org/docs/smart-contracts/tokens) along with the new assets and tokens wayfinding section. 

Ideas and comments welcome!

**Comment by janewang** [comment]
In [this thread](https://stellarfoundation.slack.com/archives/C049E67BFSP/p1712877639697069), the team discussed on renaming `Network` to `Products` on the top nav.

**Comment by briwylde08** [comment]
I created a new issue for renaming the Network section here: https://github.com/stellar/stellar-docs/issues/495

**Comment by briwylde08** [comment]
Being done with v2 of docs merge.
