### ISSUE TITLE
Change the "Network" section title

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#495]
We've had some comments that the Network title isn't the obvious location for the data availability sections (like RPC and Horizon). The section title "Products" has been suggested instead.

Other suggestions and discussion welcome.

**Comment by ElliotFriend** [comment]
I think to many devs, the title "Products" would bring to mind that these are things that must be purchased.

**Comment by rice2000** [comment]
What about "Network Infrastructure" or just "Infrastructure"?

**Comment by ElliotFriend** [comment]
I think the distinction made was that things like the anchor/disbursement platform aren't really the infrastructure that operates the network, but are more like services/applications that operate _on_ the network (if I'm remembering correctly).

**Comment by briwylde08** [comment]
Preliminary findings from @alexisdowney1 have shown that there is not a spike in people searching for RPC, Horizon, or other items listed in the Network section since the docs merge. So no data-driven motivation to change the name at this time.

**Comment by janewang** [comment]
We discussed at length during the call today and agreed on Network is too fuzzy a term for this. Based on engineering's continued feedback, we agreed on using Data or Data Service for this bucket, and move core validator out from this tab

**Comment by briwylde08** [comment]
Fixing with v2 of docs merge.
