### ISSUE TITLE
SEO: 24 External Broken Link 

### ISSUE THREAD

**Issue by alexisdowney1** [stellar/stellar-docs#498]
**About this issue**

Broken external links lead users from one website to another, bringing them to non-existent web pages. Multiple broken links negatively affect user experience and may worsen your search engine rankings because crawlers may think your website is poorly maintained or coded.
Please note that the crawler may detect a working link as broken. Generally, this happens if the server hosting the website you're referring to blocks our crawler from accessing this website.

**How to fix it**

Please follow all links reported as broken. If a target webpage returns an error, remove the link leading to the error page or replace it with another resource.
If the links reported as broken do work when accessed with a browser, leave as is or contact the website's owner and inform them about the issue.

Impact Category:HTTP Status, Links, Crawlability

cc @ElliotFriend @briwylde08 
Excel: https://docs.google.com/spreadsheets/d/1pnj_IePvpN8hip9BsEgU5_qkuzlcsQneB-7wweuozpk/edit#gid=1684482097

CSV [developers.stellar.org_external_broken_links_20240417.csv](https://github.com/stellar/stellar-docs/files/15015139/developers.stellar.org_external_broken_links_20240417.csv)

**Comment by briwylde08** [comment]
PR: https://github.com/stellar/stellar-docs/pull/499

**Comment by briwylde08** [comment]
This has been completed with the merging of https://github.com/stellar/stellar-docs/pull/499
