### ISSUE TITLE
Move Data Indexers under Data Availability

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#503]
### What problem does your feature solve?
Indexers are data providers: https://developers.stellar.org/docs/tools/developer-tools#data-indexers
They are not really developer tools. 

### What would you like to see?
Move indexers under Data Availability as a new page - See drop down menu below

<img width="250" alt="Screenshot 2024-04-18 at 10 05 13 AM" src="https://github.com/stellar/stellar-docs/assets/734336/082e3201-573e-4196-9f36-4a47c2a76446">

**Comment by briwylde08** [comment]
Also mention "aggregators"

**Comment by briwylde08** [comment]
Fixed with: https://github.com/stellar/stellar-docs/pull/541
