### ISSUE TITLE
Document changes to `getHealth` status on RPC

### ISSUE THREAD

**Issue by sydneynotthecity** [stellar/stellar-docs#515]
### What problem does your feature solve?

Please update the documentation of the `getHealth` endpoint to reflect the recent changes in the endpoint. The documentation should be part of the official docs: https://developers.stellar.org/network/soroban-rpc/methods/

**Comment by OkSang88** [comment]
Cám ơn bạn.

   NMS(Sang Nguyễn)

Vào 0:04, Th 4, 24 thg 4, 2024 sydneynotthecity ***@***.***>
đã viết:
