### ISSUE TITLE
This issue tests the bot | Bug Report

### ISSUE THREAD

**Issue by Stellar-tickets** [stellar/stellar-docs#545]
Adding some content for this issue body. Please ignore this bug as it is for testing purposes

**Comment by Stellar-tickets** [comment]
🔗 [Discuss this issue on Discord](https://discord.com/channels/897514728459468821/1237076896634634361)

**Comment by janewang** [comment]
Adding comment to this issue for testing the bot

**Comment by janewang** [comment]
closing the issue and testing out the discord bot
