### ISSUE TITLE
Build a GUI tool for fee simulation

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#598]
**Get awarded:** up to $750 worth of XLM
**Section:** Tools - Developer Tools: https://github.com/stellar/stellar-docs/blob/main/docs/tools/developer-tools.mdx - link to the tool in this section, feel free to post a link to the tool in this issue as well

**The GUI could include the following features:**

- Fee estimation - enable users to estimate fees based on current network conditions
- Fee simulation - allow users to simulate transactions with different fee settings to find optimal costs
- Fee history tracking - display historical fee data and trends

**Comment by Myestery** [comment]
@briwylde08 I'll like to work on this

**Comment by Myestery** [comment]
@briwylde08 I built this tool for this issue https://stellar-indexed.web.app/fee-estimation

**Comment by briwylde08** [comment]
Thank you! We have it in review. I gave reviewers a three-week window to check things out, but hopefully we'll be a little faster. Much appreciated!

**Comment by rahul-soshte** [comment]
Assign me this issue @briwylde08 I will be taking this head-on

**Comment by rahul-soshte** [comment]
Hi @kalepail @briwylde08 I am doing the work on this issue, had just a update and some doubts. For fee estimation I get the UX, I just need to create a flow where the user can toggle with the resource limits and fees, get the latest inclusion fee from getFeeStats() using the SDK, add them up, and estimate the fees which @kalepail also mentions it in the stellar laboratory issue here.
https://github.com/stellar/laboratory/issues/747#issue-2162459272

What I was confused was the fee simulation part, I mean if a transaction is already built and signed and simulated by sending it to the simulateTransaction endpoint, you cant really toggle with the fees of the signed transaction right? So it might make sense to change the contract code, and upload it as WASM and then do the transaction simulation to check the fees, with all the incurred resource fees and inclusion fees, posted in the UI after simulation. Just if you could more clarity on that part, that would be great. Maybe the doubt is that, what custom parameters that can be toggled with are good for transaction simulation(are they the same as fee estimation ones?), which depend on the flow of the transaction simulation in the tool, which is unclear from the description

For Fee History Tracking, I guess I can track various different various, like the inclusion Fee overtime, or the averge transaction fee during the day, and then record it everyday. I don't know how many different categories to take for that, 

I wanted to ask these doubts, so to clear out what is expected here, and make it more easier on the reviewers, so they don't think the complete UX was wrong at the end.

Guess the fidelity of this tool will be not that high, but it will be mediumish. Maybe I can create a small SCF project out of this as well later.

**Comment by rahul-soshte** [comment]
I think I might have a okay idea what is to be done in Fee Simulation.

You provide a input to mention a Contract Address, then create a Input Field for Transaction XDR, which will be the transaction that can be simulated considering the contract. Then do what [sorobill ](https://github.com/kalepail/sorobill) does, show this data as a response
{
  cpu_insns: 130351778,
  mem_bytes: 47448018,
  entry_reads: 43,
  entry_writes: 21,
  read_bytes: 143508,
  write_bytes: 68452,
  events_and_return_bytes: 8272,
  min_txn_bytes: 76132,
  max_entry_bytes: 66920,
  max_key_bytes: 352,
}

and also along with also show the breakdown of fees somehow from the response of simulateTransaction or the fee calculation algorithm used in the fee estimation. This overall idea looks okay for fee simulation and feasible, and usable.

**Comment by briwylde08** [comment]
Heya! Sorry for the lack of response here. I don't know the answer and kalepail is ooo right now. Maybe @Julian-dev28 or @ElliotFriend have some insight?

**Comment by briwylde08** [comment]
Sorry for the lack of response here. Going to see if I can find someone to help.

**Comment by kalepail** [comment]
I am on leave so won't be very responsive but I'd strongly suggest you implement Mercury/Zephyr for indexing here. It's currently free and even if/when they add paid tiers it will be simple to share indexing programs for other folks to run/host.

https://www.mercurydata.app/ 
https://www.mercurydata.app/products/zephyr-vm

There are some really good examples here https://github.com/xycloo/zephyr-examples and I personally have built one for the `passkey-kit` https://github.com/kalepail/passkey-kit/tree/main/zephyr

**Comment by rahul-soshte** [comment]
I understand @heytdep , thanks, I am going through the zephyr docs.

**Comment by heytdep** [comment]
@rahul-soshte great, if you have any questions feels free to reach out on discord (my username is heytdep) either through dm or on the stellar dev server (please tag me so I can see the notif).

**Comment by briwylde08** [comment]
Hi @rahul-soshte!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $1,000 worth of XLM (we upped it a bit)! Cam you please confirm that your personal information submitted for previous bounty submissions is still correct?

All the best,
Bri

**Comment by rahul-soshte** [comment]
Hello @briwylde08  
I confirm all my previously submitted personal information is still correct!
