### ISSUE TITLE
Create a guide for consuming previously ingested events

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#599]
**Get awarded:** up to $300 worth of XLM
**Section:** How-To Guides - Events: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/events

**Guide could include:**

- Understanding event ingestion - what is it and why is it important?
- A step-by-step code guide on how to access and consume previously ingested events 
- Demonstrate how consuming events can enhance application functionality or user experience

**Comment by tupui** [comment]
I can try to propose something. I recently looked into events for a project. Worst case, what I would write here could the person taking this further 😅

**Comment by briwylde08** [comment]
Sounds like a plan! For sure take a stab at it and let me know how it's going.

**Comment by tupui** [comment]
I started to work on this branch https://github.com/tupui/stellar-docs/blob/599_consume_events/docs/smart-contracts/guides/events/consume.mdx

So far I have written some intro and the code to have some events in an in-memory DB to consume. This already gives me the DB model to consume and I will write that tomorrow. I will also add some consideration about idempotency.

I might also propose to add some information in the reference doc itself. As I was first going through all of these, I found that the example was providing a lot more info than the reference itself. In general, I needed to have read all docs about events to really understand how all of that was working and the back and forth between all docs could maybe be limited somehow.

---

For reference, putting here some information from Discord:

> "consume meaning "actually making use of the event data in an application". like, you "ingested" and stored the data in a DB, and now you're "consuming" it by retrieving from the db, perhaps doing XDR decoding stuff along the way, and then using the previously ingested data in some way. i'm not very familiar with kafka, but i think having something on idempotent consumption would be useful content to have (though, not exactly what I had in mind by event consumption)"
> ...
> i know our guides (currently) are pretty js-heavy, but the idea is to (eventually/someday) have the same functionality demonstrated in python, js, go, whatever-else

**Comment by briwylde08** [comment]
Hi @tupui!


Congratulations!  Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $500 worth of XLM!  One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award! 


Please let us know if you have any questions. 


All the best,
Bri

**Comment by tupui** [comment]
Thanks a lot @briwylde08 🙇 I am happy that I could be helpful! I filled out the form.

**Comment by briwylde08** [comment]
Hi @tupui,

Thank you for providing the requested information! You’ve passed KYC and we’ve logged your award payment of $500 worth of XLM, which will be sent to the wallet you designated in the next week.

Please let me know if you have any questions.

All the best,
Bri

**Comment by tupui** [comment]
Thanks a lot! 😊
