### ISSUE TITLE
Create a guide for minting native XLM in a contract test

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#601]
**Get awarded:** up to $250 worth of XLM
**Section:** How-To Guides - Testing: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/testing

**Guide could include:**

- Explain why it’s important to use test environments for development
- How to set up a test environment
- Step-by-step instructions on creating a smart contract for minting XLM

**Comment by jbrainz** [comment]
Will like to work on this.

**Comment by leonmak** [comment]
I'd like to work on this

**Comment by tupui** [comment]
Potentially closed by #754 😃

**Comment by briwylde08** [comment]
Taking the conversation here: https://github.com/stellar/stellar-docs/issues/601
