### ISSUE TITLE
Create a guide explaining how to create a restoration footprint manually to restore archived data

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#603]
**Get awarded:** up to $200 worth of XLM
**Section:** How-To Guides - State Archival: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/archival

**Guide could include:**

- Explanation of state archival functionality
- Code walkthrough
- Written explanation of how the guide works

**Comment by KodeSage** [comment]
Hi @briwylde08 , I would love to work on this

**Comment by briwylde08** [comment]
Great! You got it!

**Comment by tupui** [comment]
Potentially closed by #754 😃

**Comment by tupui** [comment]
Oh sorry I misread and it was a typo. 613 it was and not this 😅

**Comment by tomita-militaru** [comment]
Hello @briwylde08 - may I work on this one?

**Comment by briwylde08** [comment]
Heya @tomita-militaru! Super glad you'd like to participate! Let's give @KodeSage a chance to respond if he's still planning on working on this before you snag it. @KodeSage -- are you still working on this issue (and I guess another question is if you will be able to submit by the deadline of Wednesday next week?)

**Comment by KodeSage** [comment]
Hi @briwylde08 , I just create a PR on it.

**Comment by briwylde08** [comment]
Hi @tomita-militaru! Feel free to take this issue!

**Comment by tomita-militaru** [comment]
@briwylde08 thank you!

**Comment by tomita-militaru** [comment]
Hi @briwylde08 - I've just submitted a PR 🤞

**Comment by briwylde08** [comment]
Thank you! We'll get it assigned and reviewed [👏](https://emojipedia.org/clapping-hands)

**Comment by briwylde08** [comment]
Hi @tomita-militaru! 

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $200 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri

**Comment by tupui** [comment]
Youhou 🥳 congrats Tomi 👏

**Comment by tomita-militaru** [comment]
Thank you!

**Comment by tomita-militaru** [comment]
Hi @briwylde08 - I've just filled in the forms, thanks!
