### ISSUE TITLE
Create guides for working with contract specs in other programming languages besides JavaScript

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#606]
**Get awarded:** up to $400 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Introduction that includes what a contract spec typically includes, explaining how these details guide the interaction with contracts through whatever programming language you’re using
- Prerequisites such as the tools, software, or libraries needed
- Tutorials on interacting with Soroban smart contracts in whatever programming language you’re using with code examples, including reading from a contract, writing to a contract, and handling events emitted from a smart contract
- Advanced topics such as upgrading contracts, interacting with multiple contracts, and more

**Comment by CaptainPrinz** [comment]
Can I work on this as well??

**Comment by briwylde08** [comment]
Hi @CaptainPrinz! Can we make sure what you're working on doesn't overlap with this existing PR? https://github.com/stellar/stellar-docs/pull/768

I'll assign this PR to @Myestery when I can.

**Comment by Myestery** [comment]
Here @briwylde08 
I have a draft PR already for it

**Comment by briwylde08** [comment]
Hi @Myestery! Can you confirm the information you've submitted for previous bounties is still accurate? Then we can log your award for this one of $400 worth of XLM.

**Comment by Myestery** [comment]
> Hi @Myestery! Can you confirm the information you've submitted for previous bounties is still accurate? Then we can log your award for this one of $400 worth of XLM.

yeah, everything remains the same 
Thanks
