### ISSUE TITLE
Create guides for working with type conversions (Address to BytesN, String to ScVal, etc.) in various programming languages

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#607]
**Get awarded:** up to $500 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Introduction that includes what type conversions are and discusses different data types like Address, BytesN, ScVal, etc., and their roles
- Code examples of converting various types in whatever programming language you’re working with
- Example scenarios where these types of conversions are used

**Comment by Mackenzie-OO7** [comment]
Hi! @briwylde08 I’d like to work on this

**Comment by briwylde08** [comment]
You got it!

**Comment by od-hunter** [comment]
Is this up for grabs? If yes, I would to be assigned please

**Comment by briwylde08** [comment]
@Mackenzie-OO7, are you still working on this? 

@od-hunter, let's give the assignee a few days to let us know if they're working on this issue still before you do any work.

**Comment by Mackenzie-OO7** [comment]
> @Mackenzie-OO7, are you still working on this?

Yes I am. Sorry I kind of got sidetracked😅. I’ll make a PR soon.

**Comment by briwylde08** [comment]
Hi @Mackenzie-OO7!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $500 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri
