### ISSUE TITLE
Create a guide on how to automate Testnet and Futurenet reset data 

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#608]
**Get awarded:** up to $200 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- An explanation of what the Testnet and Futurenet reset is and why it’s done
- Code walkthroughs on how to automate data on both networks
- Helpful information: https://developers.stellar.org/docs/learn/fundamentals/networks#test-data-automation

**Comment by KodeSage** [comment]
Hi @briwylde08 Please I would love to work on this.

**Comment by briwylde08** [comment]
Absolutely!

**Comment by rahulk002** [comment]
I would like to work on this .Is it possible?

**Comment by KodeSage** [comment]
I'm still working on it
@rahulk002

**Comment by rahulk002** [comment]
You are working on other two issues as well , none is completed .if you dont mind i would like to work on this

**Comment by briwylde08** [comment]
Hi @KodeSage! Thank you for your submission! Can you confirm that the information you've provided for past submissions is still accurate? 

Best,
Bri

**Comment by KodeSage** [comment]
> Hi @KodeSage! Thank you for your submission! Can you confirm that the information you've provided for past submissions is still accurate?
> 
> Best, Bri


Hi @briwylde08 yeah the information is still accurate. Thank you.
