### ISSUE TITLE
Create a guide for analyzing smart contract cost and efficiency

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#609]
**Get awarded:** up to $600 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**	

- Identify and explain the factors that affect smart contract performance and cost efficiency
- Review various tools and methods available for analyzing smart contract efficiency and cost
- Offer strategies and best practices for optimizing smart contract code to reduce cost and improve efficiency
- Include code examples showing inefficient versus optimized contract code

**Comment by CaptainPrinz** [comment]
Is this still available??

**Comment by Myestery** [comment]
I'm concluding work on it already #711 @CaptainPrinz

**Comment by Myestery** [comment]
@briwylde08 pls assign this too

**Comment by briwylde08** [comment]
@Myestery! Thank you for your amazing work on this. We'll get the award of $600 processed. Is the information you entered for previous bounties still correct?

**Comment by Myestery** [comment]
> @Myestery! Thank you for your amazing work on this. We'll get the award of $600 processed. Is the information you entered for previous bounties still correct?

Yes everything is the same.
Thank you
