### ISSUE TITLE
Muxed Accounts: add a warning on current state of adoption

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-docs#61]
Maybe something like:
✅ It is safe for all wallets to implement sending to muxed accounts. 
❗ If you wish to receive deposits to muxed accounts please keep in mind that they are not yet supported by all wallets and exchanges

@Shaptic @leighmcculloch thoughts?

**Comment by briwylde08** [comment]
Sounds good. Is there an easy way to figure out whether a wallet/exchange does support muxed accounts?

**Comment by leighmcculloch** [comment]
👍

**Comment by leighmcculloch** [comment]
> ❗ If you wish to receive deposits to muxed accounts please keep in mind that they are not yet supported by all wallets and exchanges

Let's also focus on encouraging continued support for memos in conjunction with murder accounts, rather than discouraging use.

**Comment by briwylde08** [comment]
Added language around supporting both memos and muxed accounts and the current state of adoption (https://github.com/stellar/stellar-docs/pull/63)
