### ISSUE TITLE
Develop smart contract init templates

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#611]
**Get awarded:** up to $200 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions
**Example:** https://github.com/stellar/soroban-cli/blob/main/docs/soroban-cli-full-docs.md#soroban-contract-init

**Guide could include:**

- A complete, ready-to-use codebase that can be deployed as-is or with minimal modifications
- Detailed instructions on how to initialize and deploy the smart contract using the provided template
- Explain how developers can customize the template to fit their specific needs

**Comment by CaptainPrinz** [comment]
I'd like to take care of this issue

**Comment by CaptainPrinz** [comment]
> **Get awarded:** up to $200 worth of XLM **Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions **Example:** https://github.com/stellar/soroban-cli/blob/main/docs/soroban-cli-full-docs.md#soroban-contract-init
> 
> **Guide could include:**
> 
> * A complete, ready-to-use codebase that can be deployed as-is or with minimal modifications
> * Detailed instructions on how to initialize and deploy the smart contract using the provided template
> * Explain how developers can customize the template to fit their specific needs

I'm ready to start working on  this if issue you're okay with it

**Comment by briwylde08** [comment]
You got it!

**Comment by rahulk002** [comment]
Can i also work on this ?

**Comment by briwylde08** [comment]
@rahulk002 - I think it's okay for multiple folks to work on the same issue, however, I'd prefer if you waited to see what @CaptainPrinz is doing so we're not duplicating work!

**Comment by CaptainPrinz** [comment]
@briwylde08 I'M done waiting for review

**Comment by briwylde08** [comment]
Hi @CaptainPrinz!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $200 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri
