### ISSUE TITLE
Integrate a Stellar asset into smart contracts using code

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#613]
**Get awarded:** up to $500 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- A detailed tutorial on how to code the integration of Stellar assets into Soroban smart contracts
- Include code examples that show how to handle Stellar asset transactions, balance queries, and other related operations within a smart contract

**Comment by tupui** [comment]
Provided you liked what I did with events, I could write something here.

I have played with Stellar assets and Soroban here https://github.com/tupui/soroban-seal-coin/blob/main/contract/src/lib.rs so I think I know what you mean here. (In terms of timeline, I can start working on that next week. This also leave time to maybe wrap up the other PR 😄)

**Comment by briwylde08** [comment]
Oh yeah that would be great. I'll give it to ya. And the program is running for 10 weeks, feel free to snag as many issues as you'd like!!

**Comment by tupui** [comment]
I am trying to start on this one and realise that there is already sort of a guide in the doc, at least the first part, with https://developers.stellar.org/docs/smart-contracts/tokens/stellar-asset-contract

(I almost forgot that I actually worked a bit on that page 😅 https://github.com/stellar/soroban-docs/pull/718)

The second point is still a bit missing. So maybe an approach would be to carve out the last section (`Using Stellar Asset Contract with other contracts`) into a guide and add the missing bits there.

I also see #601 and maybe this could fit in this guide instead as I am not sure there is much more to say on just the minting + testing bit.

What do you think?

**Comment by briwylde08** [comment]
Hi @tupui! Hmm. I actually think pulling out the `Using the `Stellar Asset Contract with other contracts` and adding the missing pieces and turning that into a separate guide makes sense. I support that!

**Comment by briwylde08** [comment]
Hi @tupui! Thank you so much for your contribution (combined with https://github.com/stellar/stellar-docs/issues/601)!! The award amount for these two issues is $750 worth of XLM. Since you've already filled out the form with your previous submission, we can just use that information. Has anything changed since your last submission?

**Comment by tupui** [comment]
Thank you @briwylde08 🙏 yes we can use the same information, nothing changed 😃

**Comment by briwylde08** [comment]
Great! We've logged your award of $750 worth of XLM which you should see in the next week! Thanks again for your amazing contributions!
