### ISSUE TITLE
Create a guide for deploying a contract from installed Wasm bytecode using code

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#614]
**Get awarded:** up to $100 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Code walkthrough
- Written explanation

**Comment by KodeSage** [comment]
HI @briwylde08 , I would love to take up this tasks.

**Comment by briwylde08** [comment]
You got it!

**Comment by briwylde08** [comment]
Hi @KodeSage!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $100 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

**Feel free to fill out the form just once for your two submissions! I'll manually fill in the second.**

Please let us know if you have any questions.

All the best,
Bri

**Comment by KodeSage** [comment]
Hi @briwylde08 , I have completed the filling of this form and submitted too.

**Comment by briwylde08** [comment]
Hi @KodeSage,

Thank you for providing the requested information! You’ve passed KYC and we’ve logged your award payment of $350 worth of XLM (we'll combine the payment with your other bounty), which will be sent to the wallet you designated in the next week.

Please let me know if you have any questions.

All the best,
Bri
