### ISSUE TITLE
Create a guide for deploying a Stellar Asset Contract for a Stellar asset using code

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#615]
**Get awarded:** up to $250 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Code walkthrough
- Written explanation

**Comment by KodeSage** [comment]
Hi @briwylde08 , I will love to work on this

**Comment by Arsalaan-Alam** [comment]
Hi @briwylde08, I can take this issue if no one is actively building it.

**Comment by briwylde08** [comment]
Hello @KodeSage! Are you still actively working on this one?

**Comment by KodeSage** [comment]
HI @briwylde08 , yeah I'm still working on it, just few drawbacks to get it to completion and I will make a PR.

**Comment by briwylde08** [comment]
No worries! Please continue your work on the issue @KodeSage! Just a reminder that the bounty ends on August 10th so we won't be accepting any PRs submitted past that date. Thank you!

**Comment by anataliocs** [comment]
@KodeSage Reviewed!  Please ping me if you have any questions about feedback

**Comment by KodeSage** [comment]
> @KodeSage Reviewed! Please ping me if you have any questions about feedback

Hello @anataliocs I have updated neccessary changes. please take a look at it again.

**Comment by briwylde08** [comment]
Thanks again @KodeSage! Can you confirm that your information is still the same as it was for your previous submissions?

**Comment by KodeSage** [comment]
> Thanks again @KodeSage! Can you confirm that your information is still the same as it was for your previous submissions?

Hi @briwylde08 , yes it's still same.

**Comment by briwylde08** [comment]
Great, we'll get your award payment processed! Thanks again for all your contributions!
