### ISSUE TITLE
Create a guide for extending a deployed contract’s Wasm code TTL with code

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#618]
**Get awarded:** up to $150 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Code walkthrough
- Written explanation

**Comment by Gift-Naomi** [comment]
@briwylde08 If this is still open I will like to be assigned

**Comment by briwylde08** [comment]
You got it.

**Comment by Myestery** [comment]
Hello @briwylde08 if this is still open, I can work on it before tomorrow

**Comment by briwylde08** [comment]
Go for it.

**Comment by briwylde08** [comment]
Awesome, we'll get your award payment of $150 worth of XLM processed!
