### ISSUE TITLE
Create a guide for installing and deploying a smart contract with code

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#619]
**Get awarded:** up to $150 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Code walkthrough
- Written explanation

**Comment by rahul-soshte** [comment]
@briwylde08 I would like to work on this issue.

**Comment by briwylde08** [comment]
Hi @rahul-soshte!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $200 worth of XLM (we upped it a bit)! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri

**Comment by rahul-soshte** [comment]
Yes @briwylde08 I have filled the form.

**Comment by briwylde08** [comment]
Thank you! And sorry for making you fill it out twice [😅](https://emojipedia.org/grinning-face-with-sweat). We'll get the payment processed within the next week!
