### ISSUE TITLE
Create a guide for installing Wasm bytecode using code

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#620]
**Get awarded:** up to $150 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Code walkthrough
- Written explanation

**Comment by leonmak** [comment]
Hi I'd like to try this

**Comment by briwylde08** [comment]
Hi there! I think this one is already being worked on here: https://github.com/stellar/stellar-docs/pull/737

**Comment by leonmak** [comment]
Hi @briwylde08 I added a js and python guide in #783

**Comment by briwylde08** [comment]
Hi @leonmak!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $200 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri

**Comment by briwylde08** [comment]
Thank you for filling out the form! You've passed KYC and we've logged your award of $200 worth of XLM, which will be sent to the wallet you indicated in the next week. Thank you again for your submission!
