### ISSUE TITLE
Expand on the `getTransaction` RPC method with SDK tutorials and examples 

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#621]
**Get awarded:** up to $200 worth of XLM
**Section:** Network - Soroban RPC - API Reference - Methods - [getTransaction](https://developers.stellar.org/network/soroban-rpc/api-reference/methods/getTransaction)
**Example:** https://developers.stellar.org/network/soroban-rpc/api-reference/methods/getLedgerEntries

**Comment by Myestery** [comment]
Hi @briwylde08 
My XLM address is GDT7ARDYZRBXXYOCSQ3MUMISTITSSRWZI6KR2A5L5Q3KB4QIZHGYMTIH
Memo/ Tag: 11151964

**Comment by briwylde08** [comment]
Hi @Myestery!

Your submission may qualify for an award of $200 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri

**Comment by briwylde08** [comment]
Hi @Myestery,

Thank you for providing the requested information! You’ve passed KYC and we’ve logged your award payment of $200 worth of XLM, which will be sent to the wallet you designated in the next week.

Please let me know if you have any questions.

All the best,
Bri
