### ISSUE TITLE
Expand on the `simulateTransaction` RPC method with SDK tutorials and examples 

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#623]
**Get awarded:** up to $200 worth of XLM
**Section:** Network - Soroban RPC - API Reference - Methods - [simulateTransaction](https://developers.stellar.org/network/soroban-rpc/api-reference/methods/simulateTransaction)
**Example:** https://developers.stellar.org/network/soroban-rpc/api-reference/methods/getLedgerEntries

**Comment by silence48** [comment]
I submitted this PR: 
Enhanced simulateTransaction Documentation #666 

Hope it helps!

Thanks

**Comment by briwylde08** [comment]
Hi @silence48!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $200 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri

**Comment by briwylde08** [comment]
Hi @silence48! Just want to confirm, we're still waiting on you to fill out the form so we can begin the award process!

**Comment by silence48** [comment]
Hi bri
I will fill it out today.
