### ISSUE TITLE
Create a guide on deploying a SAC from within a contract

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#625]
**Get awarded:** up to $250 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Code walkthrough
- Written explanation

**Comment by KoxyG** [comment]
I would love to be assigned to this @briwylde08

**Comment by rahul-soshte** [comment]
@briwylde08 Can you assign me this if its not being worked upon?

**Comment by briwylde08** [comment]
Hey! Let's give @KoxyG a chance to respond but I'll assign it to you @rahul-soshte if we don't hear back in a couple of days.

**Comment by KoxyG** [comment]
Yes, i am working on it. My apologies for the delay.

**Comment by briwylde08** [comment]
Sounds good @KoxyG! Please continue your work on the issue. Just a reminder that the bounty ends on August 10th so we won't accept any PRs submitted past that date.

**Comment by briwylde08** [comment]
https://github.com/stellar/stellar-docs/pull/862

**Comment by briwylde08** [comment]
Hi @KoxyG!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $250 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri
