### ISSUE TITLE
Create guides that demonstrate how to upgrade a contract

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#626]
**Get awarded:** up to $250 worth of XLM
**Section:** How-To Guides - Conventions: https://github.com/stellar/stellar-docs/tree/main/docs/smart-contracts/guides/conventions

**Guide could include:**

- Code walkthrough
- Written explanation

**Comment by KodeSage** [comment]
@briwylde08 I would like to assigned this issue

**Comment by KodeSage** [comment]
Hi @briwylde08 concerning this tasks and to get more clarification about it, I noticed this file in the convention folder

https://github.com/stellar/stellar-docs/blob/main/docs/smart-contracts/guides/conventions/upgrading-contracts.mdx

A Written Description of Upgrading Contracts.

Should I still work on this same file to make adjustments or should I do something new entirely on a new file?

**Comment by KodeSage** [comment]
Hello @briwylde08

**Comment by KodeSage** [comment]
Hello @briwylde08 ,I'm still waitiing for your feedback!!

**Comment by briwylde08** [comment]
Hi there! Apologies for not responding but it was the weekend! I'll look this over and get back to you.

**Comment by KodeSage** [comment]
alright @briwylde08 , I would be looking forward to it

**Comment by briwylde08** [comment]
Hi @KodeSage! Sorry for the delay. I would say work off of this existing guide, ensure everything is updated, and make adjustments that you would find useful. Let me know if you have additional questions! Thank you!

**Comment by KodeSage** [comment]
Hello @briwylde08 , I created a PR and Refrenced this Issue.

**Comment by briwylde08** [comment]
Thank you! I see the PR, we'll get it reviewed and let you know any feedback!

**Comment by KodeSage** [comment]
@briwylde08 #735 this is the PR for this Bounty Issue

**Comment by briwylde08** [comment]
Hi @KodeSage!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $250 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri

**Comment by KodeSage** [comment]
Hi @briwylde08 , I have completed the filling of this form.
