### ISSUE TITLE
Rename and update commands to use Stellar CLI in docs

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#629]
### What problem does your feature solve?
We have renamed soroban-cli to stellar-cli. All references to the CLI, name and commands are still using soroban.

### What would you like to see?
Names and commands should update accordingly in the docs to use stellar cli

**Comment by briwylde08** [comment]
https://github.com/stellar/stellar-docs/pull/633

**Comment by janewang** [comment]
This is fixed. The only remaining item is from the dapp challenge, which is blocked by changes needed in the dapp challenge. This work is tracked here: https://github.com/stellar/stellar-docs/issues/732
