### ISSUE TITLE
Rpc docs are missing the getVersionInfo fn

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-docs#632]
### What version are you using?

563df0c

### What did you do?

Go to https://developers.stellar.org/network/soroban-rpc/api-reference

<img width="1005" alt="Screenshot 2024-05-30 at 10 22 12 am" src="https://github.com/stellar/stellar-docs/assets/351529/19175d4e-79fd-4d8c-b347-fc17541e2b4b">

### What did you expect to see?

Information about the `getVersionInfo` rpc fn.

### What did you see instead?

No information about it.

### Extra info

It does appear that the endpoint exists:

```
$ curl -X POST https://soroban-testnet.stellar.org/ -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id": 0,"method":"getVersionInfo"}' | jq
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "version": "21.1.0-fcd2f0523f04279bae4502f3e3fa00ca627e6f6a",
    "commit_hash": "fcd2f0523f04279bae4502f3e3fa00ca627e6f6a",
    "build_time_stamp": "2024-05-10T11:18:38",
    "captive_core_version": "stellar-core 21.0.0.rc2 (c6f474133738ae5f6d11b07963ca841909210273)",
    "protocol_version": 21
  }
}
```

cc @stellar/platform-eng

**Comment by leighmcculloch** [comment]
This issue will possibly be addressed by:
- https://github.com/stellar/stellar-docs/issues/467

**Comment by 8012145393085** [comment]
Hello world
