### ISSUE TITLE
Improve Channel Account section

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#635]
https://developers.stellar.org/docs/learn/encyclopedia/channel-accounts could use some love. Who should use channel accounts and why? How, exactly, do they work? This section could be expanded upon.

**Comment by JFWooten4** [comment]
This implies slightly greater detail than my existing revision. Working on making clear diagrams that answer these important questions. Might we add a docs bounty for 200?

**Comment by briwylde08** [comment]
Hi @JFWooten4! You are working on channel accounts in the "Refresh Classic How-To Guides" PR, correct?

**Comment by JFWooten4** [comment]
Yes, @briwylde08. 🤝 While the [issue](#338) that PR relates to asks for only updated code examples, I think it's best we update the entire article given the importance of channel accounts. Especially for new developers learning core concepts, I'm currently detailing the wide array of relevant network elements.

**Comment by briwylde08** [comment]
Sounds good, I'll combine the two issues and up the award amount.

**Comment by briwylde08** [comment]
Closing, added to: https://github.com/stellar/stellar-docs/issues/338
