### ISSUE TITLE
Add code snippet in Java, Go, Python in  How to Issue an Asset

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#651]
Get awarded up to $200 worth of XLM

### What problem does your feature solve?

All the code snippets are for JS only until the end example which provides full examples for Java, Go, Python. Wouldn't it make sense to also include Java, Go, Python in the tiny code snippets as well?

https://developers.stellar.org/docs/issuing-assets/how-to-issue-an-asset

### What would you like to see?
Code snippet in Java, Go, Python

**Comment by briwylde08** [comment]
The whole tutorial could probably use a refresh!

**Comment by 8012145393085** [comment]
Hello world

**Comment by JFWooten4** [comment]
#657 ready for review 👍

**Comment by 8012145393085** [comment]
Hello world

**Comment by briwylde08** [comment]
Hi @JFWooten4!

Congratulations! Your contribution to Deep Dive Docs Bounty has been accepted! [🎉](https://emojipedia.org/party-popper/)
Your submission may qualify for an award of $200 worth of XLM! One last step: please fill out [this form](https://airtable.com/appOfFtPsiMxd27UZ/pagxH1WRxIpTFRGec/form) completely and accurately. Once we review the completed form and everything checks out, we will let you know the status of your potential award!

Please let us know if you have any questions.

All the best,
Bri

**Comment by briwylde08** [comment]
Hi @tupui,

Thank you for providing the requested information! You’ve passed KYC and we’ve logged your award payment of $200 worth of XLM, which will be sent to the wallet you designated in the next week.

Please let me know if you have any questions.

All the best,
Bri

**Comment by tupui** [comment]
I guess it's a typo 😉 but congrats @JFWooten4 🙌 keep them coming

**Comment by briwylde08** [comment]
Haha! I'm so sorry, I'm out of office and was copy/pasting too quickly!

**Comment by tupui** [comment]
No worries at all 😆
