### ISSUE TITLE
Create documentation on CAP-51, secp256r1 curve, webauthn, and passkey

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#652]
### What problem does your feature solve?
Coming back from offsite we need to document these concepts. Requested from ecosystem as well

Relevant link
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0051.md

**Comment by briwylde08** [comment]
On it! I'm starting on this one next week. We'll have it ready by the 18th.

**Comment by janewang** [comment]
Thank you @briwylde08!

**Comment by briwylde08** [comment]
https://github.com/stellar/stellar-docs/pull/677
