### ISSUE TITLE
Internally inconsistent docs on state archival restore

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#742]
Internally inconsistent in this doc https://developers.stellar.org/docs/learn/encyclopedia/storage/state-archival#instance 

The instance entries section bullet points mention `instance` can be restored. Then later on the same page, it says only Persistent entries can be restored.

<img width="988" alt="Screenshot 2024-07-01 at 3 49 36 PM" src="https://github.com/stellar/stellar-docs/assets/734336/ebcffc2d-293b-4220-bb3b-3b5b355f6522">

**Comment by briwylde08** [comment]
https://github.com/stellar/stellar-docs/pull/743
