### ISSUE TITLE
Add documentation for `network container start/stop/logs`

### ISSUE THREAD

**Issue by elizabethengelman** [stellar/stellar-docs#751]
The CLI includes a subcommand network container that enables users to start up the quickstart Docker image and view its logs. As far as I'm aware, this functionality hasn't been documented yet (please correct me if I'm mistaken!). I'm uncertain about the best location for these docs, but I'm happy to add them wherever necessary!

**Comment by vagxrth** [comment]
Hey, @elizabethengelman can you assign me the issue?

**Comment by Gift-Naomi** [comment]
Can I be assign on this if no one is working on it

**Comment by briwylde08** [comment]
If Elizabeth is already working on this, we'll assign it to her. TBD.

**Comment by briwylde08** [comment]
Hi @vagxrth! We'd be happy to have you work on this but I'd like to point out that this issue is not part of the docs bounty. Wanted to make sure this was clear before assigning it!

**Comment by vagxrth** [comment]
> Hi @vagxrth! We'd be happy to have you work on this but I'd like to point out that this issue is not part of the docs bounty. Wanted to make sure this was clear before assigning it!

Yeah, I would like to work on the issue. Can you tell me more about the docs bounty? I didn't know anything about the bounty so I'm curious about it.

**Comment by briwylde08** [comment]
@vagxrth I'll assign it to you! Check out docs bounty information here: https://github.com/stellar/stellar-docs?tab=readme-ov-file#welcome-to-the-deep-dive-docs-bounty-

**Comment by janewang** [comment]
This is documentation on using the Quickstart with the CLI: https://github.com/stellar/stellar-cli/blob/main/FULL_HELP_DOCS.md#stellar-network

**Comment by janewang** [comment]
Closing this ticket as it is covered here: https://developers.stellar.org/docs/tools/stellar-cli
