### ISSUE TITLE
Update Getting Started section to include Stellar Wallet Kit

### ISSUE THREAD

**Issue by briwylde08** [stellar/stellar-docs#766]
Integrate and add instructions on how to use the Stellar Wallet Kit: https://github.com/Creit-Tech/Stellar-Wallets-Kit in the [Getting Started Guide](https://soroban.stellar.org/docs/getting-started/create-an-app)

**Comment by od-hunter** [comment]
Can I be assigned this issue please?

**Comment by Gift-Naomi** [comment]
Can I be assigned now?

**Comment by od-hunter** [comment]
Thank you sir🙏🏾

**Comment by briwylde08** [comment]
Thank you so much for your interest! @od-hunter, I'll give it to you since you responded first. @Gift-Naomi, feel free to look at the other bounties available in the Docs Issues with the Docs Bounty label.

**Comment by Gift-Naomi** [comment]
@briwylde08 I just did

**Comment by briwylde08** [comment]
Hi @Gift-Naomi I'm sorry, I just assigned it to whoever answered first!

**Comment by briwylde08** [comment]
https://github.com/stellar/stellar-docs/pull/791

**Comment by earrietadev** [comment]
Kit's creator here 👋🏽 I can handle this task
