### ISSUE TITLE
Add Interactive course in Docs -> Learn ->Interactive learning page

### ISSUE THREAD

**Issue by ganesh1999** [stellar/stellar-docs#776]
### What problem does your feature solve?
DApp World has developed an engaging and free interactive learning course titled [Master Rust Smart Contract Development on Stellar](https://dapp-world.com/course/master-rust-smart-contract-development-on-stellar).

This comprehensive course features a blend of video lessons, quizzes, reading chapters, and coding assignments, offering a dynamic and efficient way to learn Soroban Rust smart contract technology. With this course, developers can master the intricacies of Soroban in a fun and interesting manner, ensuring a deeper understanding and practical application of the technology.

### What would you like to see?
Please add this course under the Stellar Dev  Docs -> Learn -> Interactive section.

### What alternatives are there?
None

**Comment by ElliotFriend** [comment]
Hi, there @ganesh1999! Thanks so much for pointing this out!

I've browsed quickly through a few of the pages in the course, and so far I'm impressed! I can certainly see a use for providing details/links/etc. I'll talk with the team about how/where to best fit it into the docs. Thanks!

**Comment by ganesh1999** [comment]
Thank you so much for your feedback! I'm glad to hear you're impressed with the course. Let me know if you need anything.

**Comment by briwylde08** [comment]
Hi there @ganesh1999! I'm getting an 504 error when trying to access the link.

**Comment by ganesh1999** [comment]
Hello @briwylde08 , Sorry for the inconvenience. We have fixed the issue please check again!

**Comment by janewang** [comment]
@anataliocs

**Comment by anataliocs** [comment]
@ganesh1999 Thanks so much for this 🚀  .  I'm currently going through the course now.  Will let you know if I have any feedback!

**Comment by ganesh1999** [comment]
@anataliocs any update on this?

**Comment by anataliocs** [comment]
@ganesh1999 I staged the changes required to add this update.

I haven't had a chance to review the course yet, but will do so early next week!

**Comment by anataliocs** [comment]
@ganesh1999 Merged 🚢

**Comment by anataliocs** [comment]
Thanks so much for all the hard work here @ganesh1999 🎉 🙏

**Comment by ganesh1999** [comment]
Thank you!!
