### ISSUE TITLE
🪙 XLM physical coin image

### ISSUE THREAD

**Issue by JFWooten4** [stellar/stellar-docs#797]
How much budget do you think this would need to succeed well?[^exp] More to the point, do you think it's even a good idea?[^ide] Will we ever have real usable digital cash,[^nak] or are we all stuck with Bitcoin's centralization, practicality, and environmental challenges? 🏭

[^exp]: I'd appreciate documentation of your perspective, such as a portfolio.
[^ide]: Or do you have another project which you think does this well already?
[^nak]: _See, e.g.,_ [section 1.2](https://github.com/orgs/WhyDRS/discussions/1), [competing technologies](https://whitepaper.io/document/0/kaspa-whitepaper), and [section 2 introduction](https://github.com/stellar/stellar-protocol/discussions/1504).

### What problem does your feature solve?
In drafting #723, it's become apparent that a large number of pages could use [visual examples](https://github.com/stellar/stellar-docs/pull/723/files?file-filters%5B%5D=.png&show-viewed-files=true) to simplify otherwise nuanced topics. 🌌

I prompted this conundrum to our [community](https://join.jfwooten4.com) in an effort to develop a coin representation of XLM that could be used in diagrams which also need to represent the network itself with the traditional Stellar logo.[^diff]

[^diff]: _See, e.g.,_ second image with a payment transaction representation (left) submitted to the network (right). While we could insert an arbitrary coin logo, I think keeping the docs constrained to XLM or `AstroToken` examples is best. Promoting community projects is a net positive and should happen in specific [instances](https://github.com/stellar/awesome-stellar/), but I don't think it's ethical to interweave our [LAYLOR Stock](https://stellar.expert/explorer/public/asset/1984803ORD-GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7-2) or logos promoting such, for example, in community docs.

However, good faith alone [was not enough](https://discord.com/channels/1102309240145707049/1102309240741310503/1260681999652229182) to incent material development efforts for something that I believe will be an asset for the community. even outside these docs.[^more]

[^more]: _See, e.g.,_ bonafide response from an artist just trying to pay their rent:
[<img width="450" alt="user-resp" src="https://github.com/user-attachments/assets/d5d0915a-42b1-4971-9c8b-9e0417a93a4f">](https://discord.gg/GT3E6kYVkZ)

### What would you like to see? 💭
A stellar digital design for a physical Lumen coin embodying the ethos of our [innovative](https://github.com/stellar/stellar-protocol/discussions/1504) humanitarian decentralized community. 🌐

[![image](https://github.com/user-attachments/assets/11f392de-548f-40b4-b368-ee871d08c8ad)](https://github.com/albertofemenias/bertocoin)

Might we collectively build something more akin to the "authoritative" Bitcoin coin for everyone to use, perhaps starting from this [primitive physical coin](https://www.cryptochips.io/products/stellar-2020-edition)? 💡 Here are some ideas for the outside text ring:

- Decentralized
- Opportunity
- Transparent
- Open Source
- Accessible
- Innovation
- Inclusive
- Quorum
- Peer-to-Peer
- Financial
- Integrity
- Unbanked
- Freedom
- Relief
- Hope
- Aid
- Unity
- Global
- Progress
- Community
- Resilience
- Empowerment
- Collaboration

Lastly, I propose that the coin should use [SDF's Schabo](https://cdn.sanity.io/files/e2r40yh6/staging/7a00843b7ca03a2f8553a40ad64d308fb286400a.pdf#page=11) with a palladium color scheme.[^pd] 

[^pd]: [Palladium](https://www.providentmetals.com/knowledge-center/collectible-coins/palladium-history.html) is a resilient platinum-group metal which is slightly darker in color than silver. 🖌 This aligns with the sole existing implementation of a physical lumen. Moreover, palladium is [~half as dense](https://www.doamore.com/platinum-vs-palladium) as platinum, which I believe epitomizes the SDF's [announcement](https://stellar.org/blog/foundation-news/sdfs-next-steps) from the first Meridian. 🌎

### What alternatives are there?
The only existing coin I could find from Cryptochips is held under copyright with "all rights reserved."

We could try to reach out to their company to acquire the rights and source files for the media. 🤝

Don't think this is ideal; maybe we could build the optimal community solution under [CC BY SA](https://creativecommons.org/licenses/by-sa/4.0/deed.en)?

**Comment by od-hunter** [comment]
I

**Comment by JFWooten4** [comment]
> Can I be assigned this?

Looks like this is a bot, which we might want to contemplate in docs bounty [assignment logic](https://github.com/stellar/stellar-docs/issues/765#issuecomment-2220411598).

Please do correct if I'm wrong. 👍🏾

**Comment by od-hunter** [comment]
I’m not a boy sir/ma. I am 100% human.

**Comment by JFWooten4** [comment]
Great @od-hunter, well then I'm happy to leave it in your skilled hands! Thank you for growing our community resources and generally building [important](https://github.com/stellar/stellar-docs/commit/dd87038eb59b46b6328bb28f07259012e75ee898) [new](https://github.com/stellar/stellar-docs/issues/765) [features](https://github.com/Creit-Tech/Stellar-Wallets-Kit/commit/0d0ec5d3d085a6e137b4d11550550cd996b4fbf9). 🖼️ Will reiterate a past note from @briwylde08 that this has not yet been assigned a docs bounty reward.

**Comment by od-hunter** [comment]
> Great @od-hunter, well then I'm happy to leave it in your skilled hands! Thank you for growing our community resources and generally building [important](https://github.com/stellar/stellar-docs/commit/dd87038eb59b46b6328bb28f07259012e75ee898) [new](https://github.com/stellar/stellar-docs/issues/765) [features](https://github.com/Creit-Tech/Stellar-Wallets-Kit/commit/0d0ec5d3d085a6e137b4d11550550cd996b4fbf9). 🖼️ Will reiterate a past note from @briwylde08 that this has not yet been assigned a docs bounty reward.

Will be waiting sir. Thank you 🙏🏾

**Comment by briwylde08** [comment]
Hi @JFWooten4! An interesting idea for sure. But it doesn't quite fit the assignment criteria for the docs bounty. Maybe something to consider if we run any other programs? Of course people are welcome to work on whatever they'd like but this won't be incentivized for the current program.

**Comment by janewang** [comment]
Is this idea for developer docs? It seems like it should fit better in a community grant?

**Comment by JFWooten4** [comment]
@janewang It's definitely something more aligned with community interests, and I'd be happy to posit the item to them directly. However, as someone who's been denied from SCF thrice, I noticed one important consideration from past initial reviewers was the team itself. As originally declared, we are currently a more lean backend-focused group of operatives, making a compelling pitch difficult since it would take funding to really solicit bids from creators...

**Comment by janewang** [comment]
I think this is a conversation worth discussing with SCF. For dev docs, I'm closing this ticket as we want to focus developer issues. This is a design ticket.

**Comment by JFWooten4** [comment]
No [Discord](https://discord.com/channels/897514728459468821/1268550807335211059/1268550897710141481) community interest. There's a lot to do throughout the ecosystem](https://github.com/stellar/scp-proofs/issues/25), and we're [actively](https://discord.com/channels/897514728459468821/907476473739354153/1262848253796286530) searching for solutions. 🤝

**Comment by JFWooten4** [comment]
@janewang Is there a high-quality version of this available anywhere?[^highlights]

**Comment by JFWooten4** [comment]
[This](https://x.com/XPHOENIXDRAGON/status/1906766430130815407) comuntiy memebr  uses the word "Pheonix " for the outside  text ing, and I've  reached otu  to  discuss  hte  osurce o f  hteir  rough  creation, alimg to Jane.
