### ISSUE TITLE
Provide  in depth coverage of the specific of Stellar-flavoured XDR types.

### ISSUE THREAD

**Issue by janewang** [stellar/stellar-docs#800]
### What problem does your feature solve?
Stellar is not using all XDR types, only limited numbers. We should describe these types to help those who want to better understand our XDR

### What would you like to see?
In this page, https://developers.stellar.org/docs/learn/encyclopedia/data-format/xdr
Describe the XDR types used in Stellar

**Comment by ElliotFriend** [comment]
Additionally, the github repo linked in [this section](https://developers.stellar.org/docs/learn/encyclopedia/data-format/xdr#x-files) is a 404, and should instead point to this repository: https://github.com/stellar/stellar-xdr

**Comment by Shaptic** [comment]
Dupe: https://github.com/stellar/stellar-docs/issues/676
