### ISSUE TITLE
Fix soroban getTransactions method documentation

### ISSUE THREAD

**Issue by einerzg** [stellar/stellar-docs#805]
### What did you do?

Reviewing the documentation of the method: 

https://developers.stellar.org/docs/data/rpc/api-reference/methods/getTransactions

I found an error in the Result, for the case of the parameters `latestLedgerCloseTime`, `oldestLedgerCloseTime`, which should be `latestLedgerCloseTimestamp` and `oldestLedgerCloseTimestamp`.

I also don't see documented the `cursor` property included in the answer.

### What did you expect to see?

Adjust the documentation to the exact response of the method.

**Comment by ElliotFriend** [comment]
Hi, @einerzg!! Thanks so much for reporting the error! We'll get this fixed up asap!
