### ISSUE TITLE
Documentation for including failed data references the wrong key

### ISSUE THREAD

**Issue by RaghavSood** [stellar/stellar-docs#88]
### What did you do?

The `include_failed` parameter on various endpoints, such as transactions and operations, is documented as `includefailed`.

Example: https://developers.stellar.org/api/resources/get-operations-by-account-id

### What did you expect to see?

The parameter key should be `include_failed`.

### What did you see instead?

The documentation reflects it as `includefailed`.

Using the parameter as documented doesn't work

With `include_failed`: https://horizon.stellar.org/accounts/GBFVU7QY6EMTYSF3WKH54CO5CE46BC72HOKZBBXH5YBJBLDVT3RNSNM2/operations?cursor=122568453843611647&limit=2&include_failed=true

With `includefailed`: https://horizon.stellar.org/accounts/GBFVU7QY6EMTYSF3WKH54CO5CE46BC72HOKZBBXH5YBJBLDVT3RNSNM2/operations?cursor=122568453843611647&limit=2&includefailed=true

The transaction `3cdbcbef533c834095cee2719b812d51394f95043e17e0f92a5251faf5b318f5` is only reflected when the correct parameter name is used, as expected

**Comment by briwylde08** [comment]
Done with https://github.com/stellar/stellar-docs/pull/89
