### ISSUE TITLE
Soroban RPC getFeeStats incomplete docs?

### ISSUE THREAD

**Issue by jopmiddelkamp** [stellar/stellar-docs#892]
### What did you expect to see?
When we open the [getFeeStats docs](https://developers.stellar.org/docs/data/rpc/api-reference/methods/getFeeStats) we expect the `getFeeStatsResult` description:
```
...
sorobanInclusionFee
object
Inclusion fee distribution statistics for Soroban transactions

    ...

    p90
    string
    90th nearest-rank fee percentile.

    p99
    string
    99th nearest-rank fee percentile

    ...

inclusionFee
object
Fee distribution statistics for Stellar (i.e. non-Soroban) transactions. Statistics are normalized per operation.

    ...

    p90
    string
    90th nearest-rank fee percentile.

    p99
    string
    99th nearest-rank fee percentile

    ...
```

To match the example result:
```
{
  "jsonrpc": "2.0",
  "id": 8675309,
  "result": {
    "sorobanInclusionFee": {
      ...
      "p90": "120",
      "p95": "190",
      "p99": "200",
      ...
    },
    "inclusionFee": {
      ...
      "p90": "100",
      "p95": "100",
      "p99": "100",
      ...
    },
    "latestLedger": 4519945
  }
}
```

### What did you see instead?
We see a difference in the Request > Result we see p95 while it is missing from the `getFeeStatsResult` description. Is one of the two incorrect or incomplete?

**Comment by janewang** [comment]
This is a bug from the API docs, thank you for raising the issue @jopmiddelkamp

**Comment by janewang** [comment]
PR to fix is here https://github.com/stellar/stellar-docs/pull/901

**Comment by janewang** [comment]
Closed by https://github.com/stellar/stellar-docs/pull/901
