### ISSUE TITLE
Cookbook Onboard (AI Assistant) integration [Feature Proposal]

### ISSUE THREAD

**Issue by ClockRide** [stellar/stellar-docs#961]
## Preview
Preview link: https://stellar-docs-cookbook.vercel.app

## Ask Cookbook AI Assistant
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Stellar resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building on Stellar, acting as an enhanced and streamlined technical documentation search tool as well as Solidity and Rust coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Stellar-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

![image](https://github.com/user-attachments/assets/481d7002-684f-4b13-828d-682d69b11d03)

**Comment by briwylde08** [comment]
As mentioned in the comment in the PR here: https://github.com/stellar/stellar-docs/pull/962, we love this idea but will most likely use the SDF maintained Stella AI bot for similar purposes.
