### ISSUE TITLE
Horizon API: Get Memo with "payments" function and avoid unnecessary "transactions" call just to get memo for the payment

### ISSUE THREAD

**Issue by alien2108** [stellar/stellar-docs#980]
### What problem does your feature solve?
Optimize number of RPC calls

### What would you like to see?
Memo of payment transaction returned with call to "payments"

### What alternatives are there?
Existing procedure requires additional "expensive" call to "transactions" just to get memo for a payment

**Comment by mollykarcher** [comment]
Please refile over in the Horizon codebase: https://github.com/stellar/go
