### ISSUE TITLE
Horizon API: "transactions" function should have a parameter to skip XDR content

### ISSUE THREAD

**Issue by alien2108** [stellar/stellar-docs#981]
### What problem does your feature solve?
Some transactions (claimable balance....) have HUGE XDR load. Like 10Mb per transaction. If you do not need XDR info it would be good to provide parameter to skip this data in return. We have seen "transactions" responses that were 800MB for a single wallet due to complete overload of XDR fields.

### What would you like to see?
Something as "xdr=true(default)/false" that would not return value of result_xdr and result_meta_xdr

**Comment by mollykarcher** [comment]
@alien2108 are you running your own Horizon instance or using SDF's? If the former, there is a configuration value that removes XDR output from all Horizon responses (`SKIP_TXMETA=true`). There is no ability to set this on a per-request basis. If you are using SDF's instance, then txmeta will be removed from all API responses starting at Protocol 22.

If you'd still like to request this feature (per-request txmeta removal), can you please refile it over in the Horizon codebase? That is over here: https://github.com/stellar/go
